services:
  flytsim:
    command: /start.sh Linux
    container_name: flytsim
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    environment:
    - DISPLAY
    - QT_X11_NO_MITSHM=1
    hostname: flytsim
    image: flytbase/flytsimv2:latest
    labels:
      com.nvidia.volumes.needed: nvidia_driver
    ports:
    - 80:80
    - 5760:5760
    - 8080:8080
    - 9000:9000
    privileged: true
    user: root
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - flytsim:/flyt
    - /run/udev:/run/udev:ro
    - nvidia_driver_384.111:/usr/local/nvidia:ro
    working_dir: /flyt
version: '3'
volumes:
  flytsim: null
  nvidia_driver_384.111:
    external: true
